### ISSUE TITLE
E2E tests are flaky

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2815]
Sometimes it fails, like this:
https://github.com/hawtio/hawtio/actions/runs/4593296569/jobs/8111604905

**Comment by tadayosi** [comment]
Can you have a look? @jsolovjo

**Comment by jsolovjo** [comment]
@tadayosi yes, I can have a look
I noticed that first run of e2e tests on jdk17 is failing, but the rerun of the job improves it

But I agree it shouldn't be like this, I will check it

**Comment by tadayosi** [comment]
@jsolovjo It occasionally fails not only on JDK17 but also on JDK11. Retrying multiple times should fix it but it shouldn't be that flaky.

**Comment by jsolovjo** [comment]
@tadayosi ok, I will check it tomorrow, I didn't know that it got worse, sorry

**Comment by jsolovjo** [comment]
Done, the tests seem stabilised

**Comment by tadayosi** [comment]
Flakiness is not yet fixed.
https://github.com/hawtio/hawtio/actions/runs/4675419767

**Comment by tadayosi** [comment]
should be fixed with #2823 finally.
